# Create a base dir
ARG FUNCTION_DIR="/var/task"
WORKDIR ${FUNCTION_DIR}
# Set workdir in the path
ENV PATH="${FUNCTION_DIR}:${PATH}"
# Coy the script
COPY script.sh ${FUNCTION_DIR}
# Copy the supervisor
RUN wget -P ${FUNCTION_DIR} https://github.com/grycap/faas-supervisor/releases/download/1.5.5/supervisor
RUN chmod +x ${FUNCTION_DIR}/supervisor
# Set it as the CMD
CMD [ "supervisor" ]